module.exports = {
  Infinity: true,
  NaN: true,
  null: true,
  undefined: true,
  Array: true,
  String: true,
  Object: true,
  console: true,
  arguments: true,
  eval: true,
  // uneval: true,
  isFinite: true,
  isNaN: true,
  parseFloat: true,
  parseInt: true,
  decodeURI: true,
  decodeURIComponent: true,
  encodeURI: true,
  escape: true,
  unescape: true,
  Function: true,
  Boolean: true,
  Symbol: true,
  Error: true,
  EvalError: true,
  // InternalError: true,
  RangeError: true,
  ReferenceError: true,
  SyntaxError: true,
  TypeError: true,
  URIError: true,
  Number: true,
  Math: true,
  Date: true,
  RegExp: true,
  Int8Array: true,
  Uint8Array: true,
  Uint8ClampedArray: true,
  Int16Array: true,
  Uint16Array: true,
  Int32Array: true,
  Uint32Array: true,
  Float32Array: true,
  Float64Array: true,
  encodeURIComponent: true,
  Map: true,
  Set: true,
  WeakMap: true,
  WeakSet: true,
  ArrayBuffer: true,
  // SharedArrayBuffer: true,
  // Atomics: true,
  DataView: true,
  JSON: true,
  Promise: true,
  // Generator: true,
  // GeneratorFunction: true,
  // Reflect: true,
  // Proxy: true,
  Intl: true
};